# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20170718_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
