# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20170720_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=1, max_length=150, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default=1, max_length=150, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.CharField(default=1, max_length=150, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=1, max_length=50, verbose_name='Fone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default=1, max_length=150, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default=1, max_length=10, verbose_name='Cep'),
            preserve_default=False,
        ),
    ]
