# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20170816_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.AddField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(default=1, max_length=50, verbose_name='Bairro'),
            preserve_default=False,
        ),
    ]
