# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-09 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20170909_0941'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('person', 'kynd')]),
        ),
    ]
