# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20170718_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomepessoa', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenomepessoa', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('cep', models.CharField(max_length=10, null=True, verbose_name='Cep')),
                ('tipologradouro', models.CharField(max_length=100, verbose_name='Tipo Logradouro')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=10, verbose_name='estado')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
            ],
            options={
                'verbose_name_plural': 'pessoasN',
                'verbose_name': 'pessoaN',
            },
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'profissões',
                'verbose_name': 'profissão',
            },
        ),
        migrations.CreateModel(
            name='ProfissoesPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissoesPessoa', to='persons.Pessoa')),
                ('profissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Profissao')),
            ],
            options={
                'verbose_name_plural': 'profissao da pessoa',
                'verbose_name': 'profissão da pessoa',
            },
        ),
        migrations.RemoveField(
            model_name='shipmentitem',
            name='shipment',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='ShipmentItem',
        ),
        migrations.AlterUniqueTogether(
            name='profissoespessoa',
            unique_together=set([('pessoa', 'profissao')]),
        ),
    ]
