# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20170718_1651'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profissoespessoa',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='profissoespessoa',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='profissoespessoa',
            name='profissao',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='Profissao',
        ),
        migrations.DeleteModel(
            name='ProfissoesPessoa',
        ),
    ]
