# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20170718_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='person',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
