# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_auto_20170718_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='address1',
            new_name='address',
        ),
    ]
