# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_auto_20170718_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='person',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='address1',
            new_name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
