# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-08 13:26
from __future__ import unicode_literals

import danibraz.checkout.validate_error_invoice
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emissao', models.DateField(verbose_name='emissao')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[danibraz.checkout.validate_error_invoice.validate_quantity], verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota', to='checkout.Invoice')),
            ],
            options={
                'verbose_name_plural': 'Itens da Nota',
                'verbose_name': 'Item da Nota',
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
            ],
            options={
                'verbose_name_plural': 'lançamentos',
                'verbose_name': 'lançamento',
            },
        ),
        migrations.CreateModel(
            name='LancamentoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('ABEV3', 'AMBEV S/A'), ('BBAS3', 'BRASIL'), ('BBDC3', 'BRADESCO 3'), ('BBDC4', 'BRADESCO 4'), ('BBSE3', 'BBSEGURIDADE'), ('BRAP4', 'BRADESPAR'), ('BRFS3', 'BRF SA'), ('BRKM5', 'BRASKEM'), ('BRML3', 'BR MALLS PAR'), ('BVMF3', 'BMFBOVESPA'), ('CCRO3', 'CCR SA'), ('CIEL3', 'CIELO'), ('CMIG4', 'CEMIG'), ('CSAN3', 'COSAN'), ('CSNA3', 'SID NACIONAL'), ('ECOR3', 'ECORODOVIAS'), ('ELET3', 'ELETROBRAS'), ('EMBR3', 'EMBRAER'), ('EQTL3', 'EQUATORIAL'), ('ESTC3', 'ESTACIO PART'), ('FIBR3', 'FIBRIA'), ('GGBR4', 'GERDAU'), ('GOAU4', 'GERDAU MET'), ('HYPE3', 'HYPERMARCAS'), ('ITSA4', 'ITAUSA'), ('ITUB4', 'ITAUUNIBANCO'), ('JBSS3', 'JBS'), ('KLBN11', 'KLABIN S/A'), ('KROT3', 'KROTON'), ('LAME4', 'LOJAS AMERIC'), ('LREN3', 'LOJAS RENNER'), ('MRVE3', 'MRV'), ('MULT3', 'MULTIPLAN'), ('NATU3', 'NATURA'), ('PCAR4', 'P.ACUCAR-CBD'), ('PETR3', 'PETROBRAS'), ('PETR4', 'PETROBRAS'), ('QUAL3', 'QUALICORP'), ('RADL3', 'RAIADROGASIL'), ('RAIL3', 'RUMO S.A.'), ('RENT3', 'LOCALIZA'), ('SANB11', 'SANTANDER BR'), ('SBSP3', 'SABESP'), ('SUZB5', 'SUZANO PAPEL'), ('TAEE11', 'TAESA'), ('UGPA3', 'ULTRAPAR'), ('USIM5', 'USIMINAS'), ('VALE3', 'VALE'), ('VIVT4', 'TELEF BRASIL'), ('WEGE3', 'WEG')], max_length=100, verbose_name='Papel')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamento_item', to='checkout.Lancamento')),
            ],
            options={
                'verbose_name_plural': 'Itens do Lancamento',
                'verbose_name': 'Item do Lançamento',
            },
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('ABEV3', 'AMBEV S/A'), ('BBAS3', 'BRASIL'), ('BBDC3', 'BRADESCO 3'), ('BBDC4', 'BRADESCO 4'), ('BBSE3', 'BBSEGURIDADE'), ('BRAP4', 'BRADESPAR'), ('BRFS3', 'BRF SA'), ('BRKM5', 'BRASKEM'), ('BRML3', 'BR MALLS PAR'), ('BVMF3', 'BMFBOVESPA'), ('CCRO3', 'CCR SA'), ('CIEL3', 'CIELO'), ('CMIG4', 'CEMIG'), ('CSAN3', 'COSAN'), ('CSNA3', 'SID NACIONAL'), ('ECOR3', 'ECORODOVIAS'), ('ELET3', 'ELETROBRAS'), ('EMBR3', 'EMBRAER'), ('EQTL3', 'EQUATORIAL'), ('ESTC3', 'ESTACIO PART'), ('FIBR3', 'FIBRIA'), ('GGBR4', 'GERDAU'), ('GOAU4', 'GERDAU MET'), ('HYPE3', 'HYPERMARCAS'), ('ITSA4', 'ITAUSA'), ('ITUB4', 'ITAUUNIBANCO'), ('JBSS3', 'JBS'), ('KLBN11', 'KLABIN S/A'), ('KROT3', 'KROTON'), ('LAME4', 'LOJAS AMERIC'), ('LREN3', 'LOJAS RENNER'), ('MRVE3', 'MRV'), ('MULT3', 'MULTIPLAN'), ('NATU3', 'NATURA'), ('PCAR4', 'P.ACUCAR-CBD'), ('PETR3', 'PETROBRAS'), ('PETR4', 'PETROBRAS'), ('QUAL3', 'QUALICORP'), ('RADL3', 'RAIADROGASIL'), ('RAIL3', 'RUMO S.A.'), ('RENT3', 'LOCALIZA'), ('SANB11', 'SANTANDER BR'), ('SBSP3', 'SABESP'), ('SUZB5', 'SUZANO PAPEL'), ('TAEE11', 'TAESA'), ('UGPA3', 'ULTRAPAR'), ('USIM5', 'USIMINAS'), ('VALE3', 'VALE'), ('VIVT4', 'TELEF BRASIL'), ('WEGE3', 'WEG')], max_length=100, verbose_name='Papel')),
                ('stock', models.PositiveSmallIntegerField(verbose_name='Estoque')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name_plural': 'Papeis',
                'verbose_name': 'Papel',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Papel'),
        ),
    ]
