# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-11 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='emissao',
            field=models.DateTimeField(verbose_name='emissao'),
        ),
    ]
