# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-26 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20171220_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='transaction_kind',
            field=models.CharField(choices=[('in', 'Entrada'), ('out', 'Saida'), ('eaj', 'Entrada de Ajuste'), ('saj', 'Saída de Ajuste')], default='out', max_length=4, verbose_name='Tipo Movimento'),
            preserve_default=False,
        ),
    ]
