# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20171031_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('ABEV3', 'AMBEV S/A'), ('BBAS3', 'BRASIL'), ('BBDC3', 'BRADESCO 3'), ('BBDC4', 'BRADESCO 4'), ('BBSE3', 'BBSEGURIDADE'), ('BRAP4', 'BRADESPAR'), ('BRFS3', 'BRF SA'), ('BRKM5', 'BRASKEM'), ('BRML3', 'BR MALLS PAR'), ('BVMF3', 'BMFBOVESPA'), ('CCRO3', 'CCR SA'), ('CIEL3', 'CIELO'), ('CMIG4', 'CEMIG'), ('CSAN3', 'COSAN'), ('CSNA3', 'SID NACIONAL'), ('ECOR3', 'ECORODOVIAS'), ('ELET3', 'ELETROBRAS'), ('EMBR3', 'EMBRAER'), ('EQTL3', 'EQUATORIAL'), ('ESTC3', 'ESTACIO PART'), ('FIBR3', 'FIBRIA'), ('GGBR4', 'GERDAU'), ('GOAU4', 'GERDAU MET'), ('HYPE3', 'HYPERMARCAS'), ('ITSA4', 'ITAUSA'), ('ITUB4', 'ITAUUNIBANCO'), ('JBSS3', 'JBS'), ('KLBN11', 'KLABIN S/A'), ('KROT3', 'KROTON'), ('LAME4', 'LOJAS AMERIC'), ('LREN3', 'LOJAS RENNER'), ('MRVE3', 'MRV'), ('MULT3', 'MULTIPLAN'), ('NATU3', 'NATURA'), ('PCAR4', 'P.ACUCAR-CBD'), ('PETR3', 'PETROBRAS'), ('PETR4', 'PETROBRAS'), ('QUAL3', 'QUALICORP'), ('RADL3', 'RAIADROGASIL'), ('RAIL3', 'RUMO S.A.'), ('RENT3', 'LOCALIZA'), ('SANB11', 'SANTANDER BR'), ('SBSP3', 'SABESP'), ('SUZB5', 'SUZANO PAPEL'), ('TAEE11', 'TAESA'), ('UGPA3', 'ULTRAPAR'), ('USIM5', 'USIMINAS'), ('VALE3', 'VALE'), ('VIVT4', 'TELEF BRASIL'), ('WEGE3', 'WEG')], max_length=100, verbose_name='Papel')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
            ],
            options={
                'verbose_name_plural': 'Itens do Lancamento',
                'verbose_name': 'Item do Lançamento',
            },
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='address',
            name='contact',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='operacao',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='papel',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='quantidade',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='lancamentoitem',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamento_item', to='checkout.Lancamento'),
        ),
    ]
