# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-26 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20171226_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota', to='checkout.Invoice'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_nota', to='checkout.Papel'),
        ),
    ]
