# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-21 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_papel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Papel'),
        ),
    ]
