# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-27 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20171226_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papel',
            name='stock',
            field=models.IntegerField(verbose_name='Estoque'),
        ),
    ]
