# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-06 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20171227_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Produto'),
        ),
    ]
