# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-01 00:58
from __future__ import unicode_literals

import danibraz.checkout.validate_error_invoice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20171128_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[danibraz.checkout.validate_error_invoice.validate_quantity], verbose_name='quantity'),
        ),
    ]
