# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-12 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_auto_20180112_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='checkout.Invoice'),
        ),
    ]
