# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-21 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('papel', models.CharField(max_length=100, verbose_name='Papel')),
                ('operacao', models.CharField(max_length=100, verbose_name='Operação')),
                ('total_cust', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Custo Total')),
            ],
            options={
                'verbose_name': 'lançamento',
                'verbose_name_plural': 'lançamentos',
            },
        ),
    ]
