# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-21 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='operacao',
            field=models.CharField(choices=[('C', 'COMPRA'), ('V', 'VENDA'), ('D', 'DIVIDENDOS'), ('S', 'SPLIT')], max_length=100, verbose_name='Operação'),
        ),
    ]
