# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-21 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0002_auto_20171021_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='quantidade',
            field=models.IntegerField(default=100, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
