# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-22 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0003_lancamento_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustoBovespa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_opcoes', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Taxa de termo/opções')),
                ('ana', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Taxa de ANA')),
                ('emolumentos', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Emolumentos')),
            ],
            options={
                'verbose_name': 'Custo Bovespa/Soma',
                'verbose_name_plural': 'Custos Bovespa/Soma',
            },
        ),
        migrations.CreateModel(
            name='CustoCblc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_liquido', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Valor líquido das operações')),
                ('taxa_liquidacao', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Taxa de liquidação')),
                ('taxa_registro', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Taxa de registro')),
            ],
            options={
                'verbose_name': 'Custo CBLC',
                'verbose_name_plural': 'Custos CBLC',
            },
        ),
        migrations.CreateModel(
            name='CustoCorretagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corretagem', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Corretagem')),
                ('iss_pis_cofins', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='ISS / PIS / COFINS')),
                ('irrf_operacoes', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='I.R.R.F. s/ operações. Base R$ 0,00')),
                ('outras_bovespa', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Outras Bovespa')),
            ],
            options={
                'verbose_name': 'Corretagem / Despesa',
                'verbose_name_plural': 'Corretagem / Despesas',
            },
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='total_cust',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Custo Total'),
        ),
        migrations.AddField(
            model_name='custocorretagem',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custo_corretagem', to='bolsa.Lancamento'),
        ),
        migrations.AddField(
            model_name='custocblc',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custo_cblc', to='bolsa.Lancamento'),
        ),
        migrations.AddField(
            model_name='custobovespa',
            name='lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custo_bovespa', to='bolsa.Lancamento'),
        ),
    ]
