# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa', '0005_division'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.RemoveField(
            model_name='lancamento',
            name='total_cust',
        ),
        migrations.AddField(
            model_name='custocblc',
            name='operacao',
            field=models.CharField(choices=[('C', 'COMPRA'), ('V', 'VENDA'), ('D', 'DIVIDENDOS'), ('S', 'SPLIT')], default='C', max_length=100, verbose_name='Operação'),
            preserve_default=False,
        ),
    ]
